### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by wesleybalvanz-wf**
- Switch unicode checks to six.text_type
 - Switch str checks to builtins.bytes checks
 - Modify tests to work with python 3
 - Run travis with both python 2.7 and 3.5

@cfstout

### CODE REVIEW

**Comment by cfstout** [comment]
Cool stuff. Appreciate the PR. Feel free to merge down 👍

**Comment by cfstout** [comment]
@joeslice do you have write access or can you comment someone who does? 🔑

**Comment by wesleybalvanz-wf** [comment]
I'm not sure I understand what you mean by merge down? I don't have permissions to merge.

**Comment by wesleybalvanz-wf** [comment]
@cfstout @joeslice Is it possible for this to be reviewed and merged? I need it for a project that I'm working on.

**Comment by cfstout** [comment]
@wesleybalvanz-wf I'll get someone who has write access to merge today.

**Comment by lwoodson** [comment]
LGTM, build passes with changes.

**Pull request merged**
